# Generated by Django 6.0.1 on 2026-01-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_designconcept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designconcept',
            name='image_url',
            field=models.ImageField(upload_to='designs/'),
        ),
    ]
