# Generated by Django 6.0.1 on 2026-01-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_designconcept_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designconcept',
            old_name='image_url',
            new_name='image',
        ),
    ]
