# Generated by Django 6.0.1 on 2026-01-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_chatroom_message_negotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attached_concept',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_uploads/'),
        ),
    ]
