# Generated by Django 6.0.1 on 2026-01-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_stockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiation',
            name='design',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'artisan')},
        ),
        migrations.DeleteModel(
            name='DesignConcept',
        ),
        migrations.DeleteModel(
            name='Negotiation',
        ),
    ]
